# Generated by Django 4.0.3 on 2022-03-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_data_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_data',
            name='class_teacher',
        ),
    ]
